"""add message status column

Revision ID: 33ec06183e1b
Revises: 1d31ea1f542c
Create Date: 2026-05-01 03:58:18.909018

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33ec06183e1b"
down_revision: str | Sequence[str] | None = "1d31ea1f542c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("status", sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "status")
    # ### end Alembic commands ###
